#!/usr/bin/env bash

case "$1" in
  logout)
    i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session!' -b 'Yes' 'i3-msg exit'
    ;;  
  lock)
    i3lock -c 000000 --nofork
    ;;  
  suspend)
    i3lock -c 000000 && systemctl suspend
    ;;  
  hibernate)
    i3lock -c 000000 && systemctl hibernate
    ;;  
  reboot)
    systemctl reboot
    ;;  
  shutdown)
    systemctl poweroff
    ;;  
  *)
    echo "Usage: $0 {logout|lock|suspend|hibernate|reboot|shutdown}"
    exit 2
esac

exit 0
